# -*- coding: utf-8 -*-
"""pcfiyat_tahmin.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqCZSbSAhpK8nZu9Zkf69Mv_40Qa80bM
"""

# --- 1. Libraries ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import kagglehub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# --- 2. Load Data ---
print("Downloading dataset from Kaggle...")
path = kagglehub.dataset_download("paperxd/all-computer-prices")

csv_file_name = 'computer_prices_all.csv'
full_file_path = os.path.join(path, csv_file_name)
df = pd.read_csv(full_file_path)

print("Dataset loaded. Data info:")
df.info()

# --- 3. Data Preprocessing ---
print("\nData preprocessing...")
sutunlari_sil = ['model', 'cpu_model', 'gpu_model']
df_temiz = df.drop(columns=sutunlari_sil)

# Splitting the 'resolution' column
df_temiz[['resolution_width', 'resolution_height']] = df_temiz['resolution'].str.split('x', expand=True).astype(int)
df_temiz = df_temiz.drop(columns=['resolution'])

# Converting categorical data to one-hot encoding
df_son_hali = pd.get_dummies(df_temiz, dtype=int)

# Separating X (Features) and y (Target)
y = df_son_hali['price']
X = df_son_hali.drop(columns='price')

# Splitting into Train and Test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Data split into {len(X_train)} train and {len(X_test)} test rows.")

# --- 4. Model 1: Linear Regression (Scikit-learn) ---
print("\nModel 1: Training Linear Regression...")
model_lr = LinearRegression()
model_lr.fit(X_train, y_train)

# Prediction and Evaluation
y_tahmin_lr = model_lr.predict(X_test)
mae_lr = mean_absolute_error(y_test, y_tahmin_lr)
r2_lr = r2_score(y_test, y_tahmin_lr)

print(f"--- Linear Regression Results ---")
print(f"R-squared (R2) Score: {r2_lr:.4f}")
print(f"Mean Absolute Error (MAE): {mae_lr:.2f} TL")

# --- 5. Model 2: Neural Network (TensorFlow) ---
print("\nModel 2: Training Neural Network (TensorFlow)...")

# Scaling data for the neural network
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model architecture
model_nn = Sequential()
model_nn.add(Dense(128, input_dim=X_train_scaled.shape[1], activation='relu'))
model_nn.add(Dense(64, activation='relu'))
model_nn.add(Dropout(0.2))
model_nn.add(Dense(32, activation='relu'))
model_nn.add(Dense(1)) # Output layer for regression

model_nn.compile(optimizer='adam', loss='mae')

# EarlyStopping to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

print("Model summary:")
model_nn.summary()

# Training the model
history = model_nn.fit(
    X_train_scaled, y_train,
    validation_data=(X_test_scaled, y_test),
    epochs=100,
    batch_size=64,
    verbose=1,
    callbacks=[early_stopping]
)

# Prediction and Evaluation
y_tahmin_nn = model_nn.predict(X_test_scaled)
mae_nn = mean_absolute_error(y_test, y_tahmin_nn)
r2_nn = r2_score(y_test, y_tahmin_nn)

print(f"\n--- Neural Network Results ---")
print(f"R-squared (R2) Score: {r2_nn:.4f}")
print(f"Mean Absolute Error (MAE): {mae_nn:.2f} TL")

# --- 6. Visualization ---
print("\nCreating and saving result graphs...")

# Graph 1: Linear Regression
plt.figure(figsize=(7, 7))
plt.scatter(y_test, y_tahmin_lr, alpha=0.3)
p1 = max(max(y_tahmin_lr), max(y_test))
p2 = min(min(y_tahmin_lr), min(y_test))
plt.plot([p1, p2], [p1, p2], 'r--', linewidth=2, label='Perfect Prediction (y=x)')
plt.xlabel("Actual Prices (y_test)")
plt.ylabel("Predicted Prices (y_pred_lr)")
plt.title("Linear Regression: Actual vs. Predicted")
plt.legend()
plt.grid(True)
plt.savefig("linear_regression_comparison.png") # Save to file

# Graph 2: Neural Network Training History
plt.figure(figsize=(7, 5))
plt.plot(history.history['loss'], label='Training Error (MAE)')
plt.plot(history.history['val_loss'], label='Validation Error (MAE)')
plt.title("Neural Network Model Training History")
plt.xlabel("Epoch Count")
plt.ylabel("Error (Loss - MAE)")
plt.legend()
plt.grid(True)
plt.savefig("nn_training_history.png") # Save to file

# Graph 3: Neural Network Predictions
plt.figure(figsize=(7, 7))
plt.scatter(y_test, y_tahmin_nn, alpha=0.3)
p1_nn = max(max(y_tahmin_nn.flatten()), max(y_test))
p2_nn = min(min(y_tahmin_nn.flatten()), max(y_test))
plt.plot([p1_nn, p2_nn], [p1_nn, p2_nn], 'r--', linewidth=2, label='Perfect Prediction (y=x)')
plt.xlabel("Actual Prices (y_test)")
plt.ylabel("Predicted Prices (y_pred_nn)")
plt.title("Neural Network: Actual vs. Predicted")
plt.legend()
plt.grid(True)
plt.savefig("neural_network_comparison.png") # Save to file

print("All processes completed. Displaying graphs.")
plt.show()